// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiMcx8rfvupxCHfMAksM5R2mm8oEA3Dvo',
    appId: '1:388228462509:web:e3b3770880ef84fa0f1324',
    messagingSenderId: '388228462509',
    projectId: 'finalflashchat-d3c01',
    authDomain: 'finalflashchat-d3c01.firebaseapp.com',
    storageBucket: 'finalflashchat-d3c01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3GxRIT_pGxDhcdLaaYOwuO3V-PvmJBXg',
    appId: '1:388228462509:android:559659997de018ab0f1324',
    messagingSenderId: '388228462509',
    projectId: 'finalflashchat-d3c01',
    storageBucket: 'finalflashchat-d3c01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC81-gAd1xFWtFR-vtAsRMwOEmzJHCUvI',
    appId: '1:388228462509:ios:d96f2c4350a97d960f1324',
    messagingSenderId: '388228462509',
    projectId: 'finalflashchat-d3c01',
    storageBucket: 'finalflashchat-d3c01.appspot.com',
    iosClientId: '388228462509-j7d9v6i16s2kfjl1hv5jhn2kqf5n5ggu.apps.googleusercontent.com',
    iosBundleId: 'com.example.zaparil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC81-gAd1xFWtFR-vtAsRMwOEmzJHCUvI',
    appId: '1:388228462509:ios:5e7231dc6d17e8da0f1324',
    messagingSenderId: '388228462509',
    projectId: 'finalflashchat-d3c01',
    storageBucket: 'finalflashchat-d3c01.appspot.com',
    iosClientId: '388228462509-c7enmv1rf6k3vik4oqttq28gjncslvnb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat',
  );
}
